# KumoCode デフォルトテーマ
name: "Default Theme"
version: "1.0.0"
description: "KumoCodeのデフォルトテーマ"

# フォント設定
fonts:
  primary: "'Noto Sans JP', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"
  code: "'Fira Code', 'Courier New', monospace"

# シンタックスハイライトテーマ
highlight_themes:
  light: "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-light.min.css"
  dark: "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/tokyo-night-dark.min.css"

# ライトモードカラー
light:
  colors:
    primary: "#6366f1"
    accent: "#ec4899"
    background: "#fafbfc"
    surface: "#ffffff"
    text_primary: "#1e293b"
    text_secondary: "#64748b"
    text_muted: "#94a3b8"
    border: "#e2e8f0"
    code_bg: "#f8fafc"
    link: "#6366f1"
    link_hover: "#4f46e5"
    header_text: "#ffffff"

  # グラデーション設定
  gradients:
    header: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"
    card_hover: "linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%)"

  # 背景画像（オプション）
  backgrounds:
    header_image: ""  # 空の場合はグラデーションのみ
    body_image: ""
    card_image: ""

# ダークモードカラー
dark:
  colors:
    primary: "#818cf8"
    accent: "#f472b6"
    background: "#0f172a"
    surface: "#1e293b"
    text_primary: "#f1f5f9"
    text_secondary: "#cbd5e1"
    text_muted: "#94a3b8"
    border: "#334155"
    code_bg: "#1e293b"
    link: "#818cf8"
    link_hover: "#a5b4fc"
    header_text: "#cbd5e1"

  gradients:
    header: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"
    card_hover: "linear-gradient(135deg, rgba(129, 140, 248, 0.1) 0%, rgba(244, 114, 182, 0.1) 100%)"

  backgrounds:
    header_image: ""
    body_image: ""
    card_image: ""

# 追加のスタイル設定
styles:
  border_radius: "12px"
  card_shadow: "0 4px 6px rgba(0, 0, 0, 0.1)"
  header_height: "80px"
  backdrop_blur: "10px"
